[package]
name = "postal_service"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
lazy_static = "1.4"
csv = "1.2"
rayon = "1.7"
num_cpus = "1.15"
